// ─────────────────────────────────────────────
//  Ethyne Language — JavaScript Code Generator
//
//  Transpiles the AST into clean, readable JS.
//  The output is valid Node.js that can be saved
//  as .js and run with `node`.
//
//  bol  → console.log(...)
//  pet  → let ...
//  kali → null
//  tru  → true
//  nahi → false
// ─────────────────────────────────────────────

const { EthyneError } = require('../errors/EthyneError');

class CodeGen {
  constructor(filename = '<stdin>') {
    this.filename = filename;
    this.indent   = 0;
  }

  // ── Helpers ──────────────────────────────────

  pad() { return '  '.repeat(this.indent); }

  indented(fn) {
    this.indent++;
    const result = fn();
    this.indent--;
    return result;
  }

  error(msg, node) {
    throw new EthyneError('CodeGenError', msg, node?.line ?? 0, node?.col ?? 0, this.filename);
  }

  // ── Entry point ──────────────────────────────

  generate(program) {
    const lines = program.body.map(n => this.genStmt(n));
    return [
      `// Generated by the Ethyne compiler`,
      `// Do not edit this file directly`,
      ``,
      ...lines,
    ].join('\n');
  }

  // ── Statements ───────────────────────────────

  genStmt(node) {
    switch (node.type) {
      case 'VarDecl':   return this.genVarDecl(node);
      case 'PrintStmt': return this.genPrint(node);
      case 'InputStmt': return this.genInput(node);
      case 'IfStmt':    return this.genIf(node);
      case 'WhileStmt': return this.genWhile(node);
      case 'FuncDecl':  return this.genFuncDecl(node);
      case 'ReturnStmt':return this.genReturn(node);
      case 'BlockStmt': return this.genBlock(node);
      case 'ExprStmt':  return `${this.pad()}${this.genExpr(node.expr)};`;
      default: this.error(`Unknown statement node '${node.type}'`, node);
    }
  }

  genVarDecl(node) {
    const init = node.init ? ` = ${this.genExpr(node.init)}` : '';
    return `${this.pad()}let ${node.name}${init};`;
  }

  genPrint(node) {
    return `${this.pad()}console.log(${this.genExpr(node.expr)});`;
  }

  genInput(node) {
    // adg in a transpiled context needs readline; we emit a helper call
    const prompt = node.prompt ? JSON.stringify(node.prompt + ' ') : '""';
    return [
      `${this.pad()}// adg: read input into '${node.name}'`,
      `${this.pad()}let ${node.name} = __ethyneInput(${prompt});`,
    ].join('\n');
  }

  genIf(node) {
    const test = this.genExpr(node.test);
    const cons = this.genBlock(node.consequent);
    let out = `${this.pad()}if (${test}) ${cons.trimStart()}`;
    if (node.alternate) {
      if (node.alternate.type === 'IfStmt') {
        out += ` else ${this.genIf(node.alternate).trimStart()}`;
      } else {
        out += ` else ${this.genBlock(node.alternate).trimStart()}`;
      }
    }
    return out;
  }

  genWhile(node) {
    const test = this.genExpr(node.test);
    const body = this.genBlock(node.body);
    return `${this.pad()}while (${test}) ${body.trimStart()}`;
  }

  genFuncDecl(node) {
    const params = node.params.join(', ');
    const body   = this.genBlock(node.body);
    return `${this.pad()}function ${node.name}(${params}) ${body.trimStart()}`;
  }

  genReturn(node) {
    const val = node.expr ? ` ${this.genExpr(node.expr)}` : '';
    return `${this.pad()}return${val};`;
  }

  genBlock(node) {
    const stmts = this.indented(() =>
      node.body.map(s => this.genStmt(s)).join('\n')
    );
    return `${this.pad()}{\n${stmts}\n${this.pad()}}`;
  }

  // ── Expressions ──────────────────────────────

  genExpr(node) {
    switch (node.type) {
      case 'NumberLit':  return String(node.value);
      case 'StringLit':  return JSON.stringify(node.value);
      case 'BoolLit':    return node.value ? 'true' : 'false';
      case 'NullLit':    return 'null';
      case 'Identifier': return node.name;
      case 'AssignExpr': return `${node.name} = ${this.genExpr(node.value)}`;
      case 'BinaryExpr': return `(${this.genExpr(node.left)} ${node.op} ${this.genExpr(node.right)})`;
      case 'UnaryExpr':  return `(${node.op}${this.genExpr(node.operand)})`;
      case 'CallExpr': {
        const callee = this.genExpr(node.callee);
        const args   = node.args.map(a => this.genExpr(a)).join(', ');
        return `${callee}(${args})`;
      }
      default: this.error(`Unknown expression node '${node.type}'`, node);
    }
  }
}

module.exports = { CodeGen };
